/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20 } from "./Erc20";
export type { LenderAbi } from "./LenderAbi";

export { Erc20__factory } from "./factories/Erc20__factory";
export { LenderAbi__factory } from "./factories/LenderAbi__factory";
